name: Submit Rule
description: Submit a new rule or resource to the navigation site
title: "[Rule]: "
labels: ["rule", "pending-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to our rules navigation site! Please fill out the information below to submit a new rule.
        
        感谢您为规则导航站点做出贡献！请填写以下信息以提交新规则。
  - type: input
    id: name
    attributes:
      label: Rule Name / 规则名称
      description: Enter a concise and descriptive name for the rule
      placeholder: e.g. Deno Integration
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description / 描述
      description: Provide a detailed description of the rule or resource
      placeholder: This project provides automation scripts and workflows...
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL / 链接
      description: The URL path for the article or resource (starting with /)
      placeholder: /article/your-article-slug
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category / 分类
      description: Select the main category for this rule
      options:
        - backend
        - css
        - database
        - frontend
        - language
        - mobile
        - state
        - testing
        - tools
    validations:
      required: true
  - type: input
    id: tags
    attributes:
      label: Tags / 标签
      description: Enter tags separated by commas
      placeholder: e.g. Deno, Automation, Workflow
    validations:
      required: false
  - type: textarea
    id: template
    attributes:
      label: Rule Template / 规则模板
      description: |
        Enter your rule template in markdown format. You can use the following structure:
        ```
        # Rule Name
        
        ## Description
        Describe what this rule does
        
        ## Example
        Show example usage
        
        ## Tips
        Additional tips or notes
        ```
      placeholder: |
        # My Rule Template
        
        ## Description
        This rule helps to...
        
        ## Example
        ```javascript
        // Your example code here
        ```
        
        ## Tips
        - Tip 1
        - Tip 2
      render: markdown
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Submission Agreement / 提交协议
      description: By submitting this rule, you agree to our contribution guidelines
      options:
        - label: I confirm this is my original work or I have permission to share it
          required: true
        - label: I agree that this submission will be licensed under the project's license
          required: true
