name: Submit Blog Post
description: Submit a new blog post to the site
title: "Post: "
labels: ["blog"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing to our blog! Please fill out the information below to submit a new post.
   